{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "166b7964-90a5-4a69-bb2b-c9557ee29683",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "import random\n",
    "\n",
    "class TicTacToeApp:\n",
    "    def __init__(self, master):\n",
    "        self.master = master\n",
    "        master.title(\"🎲 Tic-Tac-Toe\")\n",
    "        master.config(bg=\"#34495e\")\n",
    "        master.resizable(False, False)\n",
    "\n",
    "        # state\n",
    "        self.mode = None  # \"single\" or \"two\"\n",
    "        self.score = {\"X\": 0, \"O\": 0, \"Draw\": 0}\n",
    "\n",
    "        # start at menu\n",
    "        self._show_menu()\n",
    "\n",
    "    # ──── MENU ─────────────────────────────────────────────────────────────────\n",
    "    def _show_menu(self):\n",
    "        # destroy previous frames if any\n",
    "        for widget in self.master.winfo_children():\n",
    "            widget.destroy()\n",
    "\n",
    "        self.menu_frame = tk.Frame(self.master, bg=\"#34495e\")\n",
    "        self.menu_frame.pack(fill=\"both\", expand=True)\n",
    "\n",
    "        title = tk.Label(\n",
    "            self.menu_frame,\n",
    "            text=\"Tic-Tac-Toe\",\n",
    "            font=(\"Verdana\", 32, \"bold\"),\n",
    "            bg=\"#34495e\",\n",
    "            fg=\"white\",\n",
    "            pady=20\n",
    "        )\n",
    "        title.pack()\n",
    "\n",
    "        tk.Button(\n",
    "            self.menu_frame,\n",
    "            text=\"Single Player\",\n",
    "            font=(\"Verdana\", 16),\n",
    "            bg=\"#3498db\",\n",
    "            fg=\"black\",           # font color black\n",
    "            activebackground=\"#2980b9\",\n",
    "            width=20,\n",
    "            pady=10,\n",
    "            command=lambda: self._start_game(\"single\")\n",
    "        ).pack(pady=10)\n",
    "\n",
    "        tk.Button(\n",
    "            self.menu_frame,\n",
    "            text=\"Two Players\",\n",
    "            font=(\"Verdana\", 16),\n",
    "            bg=\"#2ecc71\",\n",
    "            fg=\"black\",\n",
    "            activebackground=\"#27ae60\",\n",
    "            width=20,\n",
    "            pady=10,\n",
    "            command=lambda: self._start_game(\"two\")\n",
    "        ).pack(pady=10)\n",
    "\n",
    "    # ──── SETUP GAME SCREEN ────────────────────────────────────────────────────\n",
    "    def _start_game(self, mode):\n",
    "        self.mode = mode\n",
    "        self.menu_frame.destroy()\n",
    "        self._build_game()\n",
    "\n",
    "        # randomize who starts in single-player\n",
    "        if self.mode == \"single\":\n",
    "            # X = human, O = computer\n",
    "            self.current = random.choice([\"X\", \"O\"])\n",
    "            if self.current == \"O\":\n",
    "                self.status.config(text=\"Computer’s turn\")\n",
    "                self.master.after(300, self._ai_move)\n",
    "            else:\n",
    "                self.status.config(text=\"Player X’s turn\")\n",
    "        else:\n",
    "            # always X starts in two-player\n",
    "            self.current = \"X\"\n",
    "            self.status.config(text=\"Player X’s turn\")\n",
    "\n",
    "    def _build_game(self):\n",
    "        # container for all game widgets\n",
    "        self.game_frame = tk.Frame(self.master, bg=\"#34495e\")\n",
    "        self.game_frame.pack(fill=\"both\", expand=True, padx=20, pady=20)\n",
    "\n",
    "        # Scoreboard\n",
    "        sf = tk.Frame(self.game_frame, bg=\"#34495e\")\n",
    "        sf.pack()\n",
    "        self.score_labels = {}\n",
    "        for who in (\"X\", \"O\", \"Draw\"):\n",
    "            lbl = tk.Label(\n",
    "                sf,\n",
    "                text=f\"{who}: {self.score[who]}\",\n",
    "                font=(\"Verdana\", 14, \"bold\"),\n",
    "                bg=\"#34495e\",\n",
    "                fg=\"#ecf0f1\",\n",
    "                width=8\n",
    "            )\n",
    "            lbl.pack(side=\"left\", padx=5)\n",
    "            self.score_labels[who] = lbl\n",
    "\n",
    "        # Status (will update in _start_game)\n",
    "        self.status = tk.Label(\n",
    "            self.game_frame,\n",
    "            text=\"\",\n",
    "            font=(\"Verdana\", 14),\n",
    "            bg=\"#34495e\",\n",
    "            fg=\"#f1c40f\",\n",
    "            pady=10\n",
    "        )\n",
    "        self.status.pack()\n",
    "\n",
    "        # Canvas\n",
    "        self.canvas_size = 300\n",
    "        self.cell = self.canvas_size // 3\n",
    "        self.canvas = tk.Canvas(\n",
    "            self.game_frame,\n",
    "            width=self.canvas_size,\n",
    "            height=self.canvas_size,\n",
    "            bg=\"#ecf0f1\",\n",
    "            highlightthickness=0\n",
    "        )\n",
    "        self.canvas.pack(pady=10)\n",
    "        self.canvas.bind(\"<Button-1>\", self._on_click)\n",
    "        self._draw_grid()\n",
    "\n",
    "        # Controls\n",
    "        ctrl = tk.Frame(self.game_frame, bg=\"#34495e\")\n",
    "        ctrl.pack(pady=10)\n",
    "        tk.Button(\n",
    "            ctrl,\n",
    "            text=\"↻ Restart\",\n",
    "            font=(\"Verdana\", 12, \"bold\"),\n",
    "            bg=\"#e74c3c\",\n",
    "            fg=\"white\",\n",
    "            activebackground=\"#c0392b\",\n",
    "            padx=10, pady=5,\n",
    "            command=self._reset_board\n",
    "        ).pack(side=\"left\", padx=5)\n",
    "        tk.Button(\n",
    "            ctrl,\n",
    "            text=\"🏠 Main Menu\",\n",
    "            font=(\"Verdana\", 12, \"bold\"),\n",
    "            bg=\"#95a5a6\",\n",
    "            fg=\"white\",\n",
    "            activebackground=\"#7f8c8d\",\n",
    "            padx=10, pady=5,\n",
    "            command=self._back_to_menu\n",
    "        ).pack(side=\"left\", padx=5)\n",
    "\n",
    "        # prepare board state; current is set in _start_game\n",
    "        self.board = [[None]*3 for _ in range(3)]\n",
    "        self.game_over = False\n",
    "\n",
    "    # ──── GRID & DRAWING ───────────────────────────────────────────────────────\n",
    "    def _draw_grid(self):\n",
    "        kw = {\"width\":4, \"fill\":\"#2c3e50\"}\n",
    "        for i in (1,2):\n",
    "            xy = i*self.cell\n",
    "            self.canvas.create_line(xy,0, xy,self.canvas_size, **kw)\n",
    "            self.canvas.create_line(0,xy, self.canvas_size,xy, **kw)\n",
    "\n",
    "    def _on_click(self, evt):\n",
    "        if self.game_over: \n",
    "            return\n",
    "        r, c = evt.y//self.cell, evt.x//self.cell\n",
    "        if self.board[r][c] is not None: \n",
    "            return\n",
    "        # if computer starts and it's O's turn, ignore clicks\n",
    "        if self.mode==\"single\" and self.current==\"O\":\n",
    "            return\n",
    "        self._place(r, c, self.current)\n",
    "        if self._check(self.current): \n",
    "            return\n",
    "        if all(all(row) for row in self.board):\n",
    "            self._finish(\"Draw\")\n",
    "            return\n",
    "        if self.mode == \"single\":\n",
    "            if self.current==\"X\":\n",
    "                # human just moved, now AI\n",
    "                self.master.after(300, self._ai_move)\n",
    "            else:\n",
    "                # shouldn’t click during AI turn\n",
    "                return\n",
    "        else:\n",
    "            self.current = \"O\" if self.current==\"X\" else \"X\"\n",
    "            self.status.config(text=f\"Player {self.current}’s turn\")\n",
    "\n",
    "    def _place(self, r, c, p):\n",
    "        pad = 20\n",
    "        x1, y1 = c*self.cell+pad, r*self.cell+pad\n",
    "        x2 = (c+1)*self.cell - pad\n",
    "        y2 = (r+1)*self.cell - pad\n",
    "        if p==\"X\":\n",
    "            self.canvas.create_line(x1,y1,x2,y2, width=6, fill=\"#2980b9\", capstyle=\"round\")\n",
    "            self.canvas.create_line(x1,y2,x2,y1, width=6, fill=\"#2980b9\", capstyle=\"round\")\n",
    "        else:\n",
    "            self.canvas.create_oval(x1,y1,x2,y2, width=6, outline=\"#c0392b\")\n",
    "        self.board[r][c] = p\n",
    "\n",
    "    # ──── AI ────────────────────────────────────────────────────────────────────\n",
    "    def _ai_move(self):\n",
    "        if self.game_over: \n",
    "            return\n",
    "        empties = [(r,c) for r in range(3) for c in range(3) if self.board[r][c] is None]\n",
    "        if not empties: \n",
    "            return\n",
    "        r,c = random.choice(empties)\n",
    "        self._place(r, c, \"O\")\n",
    "        if not self._check(\"O\"):\n",
    "            if all(all(row) for row in self.board):\n",
    "                self._finish(\"Draw\")\n",
    "            else:\n",
    "                self.current = \"X\"\n",
    "                self.status.config(text=\"Player X’s turn\")\n",
    "\n",
    "    # ──── WIN / DRAW ─────────────────────────────────────────────────────────────\n",
    "    def _check(self, p):\n",
    "        lines = [\n",
    "            [(0,0),(0,1),(0,2)], [(1,0),(1,1),(1,2)], [(2,0),(2,1),(2,2)],\n",
    "            [(0,0),(1,0),(2,0)], [(0,1),(1,1),(2,1)], [(0,2),(1,2),(2,2)],\n",
    "            [(0,0),(1,1),(2,2)], [(0,2),(1,1),(2,0)],\n",
    "        ]\n",
    "        for ln in lines:\n",
    "            if all(self.board[r][c]==p for r,c in ln):\n",
    "                self._highlight(ln)\n",
    "                self._finish(p)\n",
    "                return True\n",
    "        return False\n",
    "\n",
    "    def _highlight(self, ln):\n",
    "        (r1,c1),_,(r3,c3) = ln\n",
    "        xs = c1*self.cell + self.cell//2\n",
    "        ys = r1*self.cell + self.cell//2\n",
    "        xe = c3*self.cell + self.cell//2\n",
    "        ye = r3*self.cell + self.cell//2\n",
    "        self.canvas.create_line(xs,ys, xe,ye,\n",
    "                                width=8, fill=\"#f1c40f\", capstyle=\"round\")\n",
    "\n",
    "    def _finish(self, who):\n",
    "        self.game_over = True\n",
    "        if who==\"Draw\":\n",
    "            self.status.config(text=\"🤝 It’s a draw!\")\n",
    "            self.score[\"Draw\"] += 1\n",
    "        else:\n",
    "            self.status.config(text=f\"🎉 {who} wins!\")\n",
    "            self.score[who] += 1\n",
    "        for who,lbl in self.score_labels.items():\n",
    "            lbl.config(text=f\"{who}: {self.score[who]}\")\n",
    "\n",
    "    # ──── CONTROLS ──────────────────────────────────────────────────────────────\n",
    "    def _reset_board(self):\n",
    "        self.canvas.delete(\"all\")\n",
    "        self._draw_grid()\n",
    "        self.board = [[None]*3 for _ in range(3)]\n",
    "        # re-randomize start if single player\n",
    "        if self.mode==\"single\":\n",
    "            self.current = random.choice([\"X\",\"O\"])\n",
    "            if self.current==\"O\":\n",
    "                self.status.config(text=\"Computer’s turn\")\n",
    "                self.master.after(300, self._ai_move)\n",
    "            else:\n",
    "                self.status.config(text=\"Player X’s turn\")\n",
    "        else:\n",
    "            self.current = \"X\"\n",
    "            self.status.config(text=\"Player X’s turn\")\n",
    "        self.game_over = False\n",
    "\n",
    "    def _back_to_menu(self):\n",
    "        self.game_frame.destroy()\n",
    "        self._show_menu()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    TicTacToeApp(root)\n",
    "    root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "504c307b-8625-4003-8ae8-fa0bc8b264c1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
