{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28f01852-c001-4c7a-86a4-2f5bd27261f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "import random\n",
    "\n",
    "class WhackAMoleDeluxe:\n",
    "    def __init__(self, master):\n",
    "        self.master = master\n",
    "        master.title(\"🐹 Whack-A-Mole Deluxe\")\n",
    "        master.geometry(\"650x800\")\n",
    "        master.resizable(False, False)\n",
    "        master.config(bg=\"#2ecc71\")  # grass-green\n",
    "\n",
    "        # game params\n",
    "        self.rows = 3\n",
    "        self.cols = 3\n",
    "        self.canvas_size = 600\n",
    "        self.cell = self.canvas_size // self.rows\n",
    "        self.initial_time = 30\n",
    "\n",
    "        # state\n",
    "        self.score = 0\n",
    "        self.time_left = self.initial_time\n",
    "        self.current_mole = None\n",
    "        self.mole_id = None\n",
    "        self.hit_id = None\n",
    "        self.timer_job = None\n",
    "        self.mole_job = None\n",
    "        self.game_over = False\n",
    "\n",
    "        # start screen\n",
    "        self._show_start()\n",
    "\n",
    "    def _show_start(self):\n",
    "        self.start_frame = tk.Frame(self.master, bg=\"#2ecc71\")\n",
    "        self.start_frame.pack(fill=\"both\", expand=True)\n",
    "\n",
    "        tk.Label(\n",
    "            self.start_frame,\n",
    "            text=\"🐹 Whack-A-Mole Deluxe\",\n",
    "            font=(\"Comic Sans MS\", 36, \"bold\"),\n",
    "            fg=\"black\",\n",
    "            bg=\"#2ecc71\"\n",
    "        ).pack(pady=50)\n",
    "\n",
    "        tk.Button(\n",
    "            self.start_frame,\n",
    "            text=\"▶ Start Game\",\n",
    "            font=(\"Verdana\", 18, \"bold\"),\n",
    "            bg=\"#3498db\",\n",
    "            fg=\"black\",\n",
    "            activebackground=\"#2980b9\",\n",
    "            padx=20,\n",
    "            pady=10,\n",
    "            command=self._start_game\n",
    "        ).pack(pady=20)\n",
    "\n",
    "    def _start_game(self):\n",
    "        self.start_frame.destroy()\n",
    "        self._build_ui()\n",
    "        self._reset_state()\n",
    "        self._start_loops()\n",
    "\n",
    "    def _build_ui(self):\n",
    "        # top UI: score, timer bar & numeric timer\n",
    "        ui_frame = tk.Frame(self.master, bg=\"#2ecc71\")\n",
    "        ui_frame.pack(pady=10)\n",
    "\n",
    "        # Score label\n",
    "        self.score_label = tk.Label(\n",
    "            ui_frame,\n",
    "            text=f\"Score: {self.score}\",\n",
    "            font=(\"Verdana\", 20, \"bold\"),\n",
    "            bg=\"#2ecc71\",\n",
    "            fg=\"black\"\n",
    "        )\n",
    "        self.score_label.pack(side=\"left\", padx=10)\n",
    "\n",
    "        # Time label\n",
    "        self.time_label = tk.Label(\n",
    "            ui_frame,\n",
    "            text=f\"Time: {self.time_left}s\",\n",
    "            font=(\"Verdana\", 20, \"bold\"),\n",
    "            bg=\"#2ecc71\",\n",
    "            fg=\"black\"\n",
    "        )\n",
    "        self.time_label.pack(side=\"left\", padx=10)\n",
    "\n",
    "        # Timer bar\n",
    "        self.time_canvas = tk.Canvas(\n",
    "            ui_frame,\n",
    "            width=self.canvas_size,\n",
    "            height=20,\n",
    "            bg=\"#bdc3c7\",\n",
    "            highlightthickness=0\n",
    "        )\n",
    "        self.time_canvas.pack(side=\"left\", padx=10)\n",
    "        self.time_bar = self.time_canvas.create_rectangle(\n",
    "            0, 0, self.canvas_size, 20,\n",
    "            fill=\"#e74c3c\", width=0\n",
    "        )\n",
    "\n",
    "        # game canvas\n",
    "        self.canvas = tk.Canvas(\n",
    "            self.master,\n",
    "            width=self.canvas_size,\n",
    "            height=self.canvas_size,\n",
    "            bg=\"#2ecc71\",\n",
    "            highlightthickness=0\n",
    "        )\n",
    "        self.canvas.pack()\n",
    "        self.canvas.bind(\"<Button-1>\", self._whack)\n",
    "\n",
    "        # draw holes\n",
    "        for r in range(self.rows):\n",
    "            for c in range(self.cols):\n",
    "                x1 = c*self.cell + 20\n",
    "                y1 = r*self.cell + 20\n",
    "                x2 = (c+1)*self.cell - 20\n",
    "                y2 = (r+1)*self.cell - 20\n",
    "                self.canvas.create_oval(x1, y1, x2, y2,\n",
    "                                        fill=\"#8B4513\", outline=\"\")\n",
    "\n",
    "        # controls\n",
    "        ctrl = tk.Frame(self.master, bg=\"#2ecc71\")\n",
    "        ctrl.pack(pady=10)\n",
    "        tk.Button(\n",
    "            ctrl,\n",
    "            text=\"🔄 Restart\",\n",
    "            font=(\"Verdana\", 16, \"bold\"),\n",
    "            bg=\"#e67e22\",\n",
    "            fg=\"black\",\n",
    "            activebackground=\"#d35400\",\n",
    "            padx=15, pady=8,\n",
    "            command=self._on_restart\n",
    "        ).pack()\n",
    "\n",
    "    def _reset_state(self):\n",
    "        # reset values\n",
    "        self.score = 0\n",
    "        self.time_left = self.initial_time\n",
    "        self.current_mole = None\n",
    "        self.game_over = False\n",
    "        # clear any existing mole/hit\n",
    "        if self.mole_id:\n",
    "            self.canvas.delete(self.mole_id)\n",
    "        if self.hit_id:\n",
    "            self.canvas.delete(self.hit_id)\n",
    "        # update UI\n",
    "        self.score_label.config(text=f\"Score: {self.score}\")\n",
    "        self.time_label.config(text=f\"Time: {self.time_left}s\")\n",
    "        self.time_canvas.coords(self.time_bar, 0, 0,\n",
    "                                self.canvas_size, 20)\n",
    "\n",
    "    def _start_loops(self):\n",
    "        self._update_timer()\n",
    "        self._show_mole()\n",
    "\n",
    "    def _update_timer(self):\n",
    "        if self.time_left > 0:\n",
    "            # shrink time bar\n",
    "            ratio = self.time_left / self.initial_time\n",
    "            new_width = int(self.canvas_size * ratio)\n",
    "            self.time_canvas.coords(self.time_bar, 0, 0,\n",
    "                                    new_width, 20)\n",
    "            # decrement & update numeric display\n",
    "            self.time_left -= 1\n",
    "            self.time_label.config(text=f\"Time: {self.time_left}s\")\n",
    "            self.timer_job = self.master.after(1000,\n",
    "                                               self._update_timer)\n",
    "        else:\n",
    "            self._end_game()\n",
    "\n",
    "    def _show_mole(self):\n",
    "        # clear previous\n",
    "        if self.mole_id:\n",
    "            self.canvas.delete(self.mole_id)\n",
    "            self.mole_id = None\n",
    "            self.current_mole = None\n",
    "        if not self.game_over:\n",
    "            # choose slot\n",
    "            r = random.randint(0, self.rows-1)\n",
    "            c = random.randint(0, self.cols-1)\n",
    "            cx = c*self.cell + self.cell//2\n",
    "            cy = r*self.cell + self.cell//2\n",
    "            self.current_mole = (r, c)\n",
    "            self.mole_id = self.canvas.create_text(\n",
    "                cx, cy, text=\"🐹\",\n",
    "                font=(\"Arial\", 48),\n",
    "                fill=\"black\"\n",
    "            )\n",
    "            # schedule next\n",
    "            interval = random.randint(500, 1000)\n",
    "            self.mole_job = self.master.after(interval,\n",
    "                                              self._show_mole)\n",
    "\n",
    "    def _whack(self, event):\n",
    "        if self.game_over:\n",
    "            return\n",
    "        r = event.y // self.cell\n",
    "        c = event.x // self.cell\n",
    "        if (r, c) == self.current_mole:\n",
    "            # hit!\n",
    "            self.score += 1\n",
    "            self.score_label.config(text=f\"Score: {self.score}\")\n",
    "            self._show_hit(r, c)\n",
    "            # remove mole\n",
    "            if self.mole_id:\n",
    "                self.canvas.delete(self.mole_id)\n",
    "                self.mole_id = None\n",
    "            self.current_mole = None\n",
    "\n",
    "    def _show_hit(self, r, c):\n",
    "        cx = c*self.cell + self.cell//2\n",
    "        cy = r*self.cell + self.cell//2\n",
    "        self.hit_id = self.canvas.create_text(\n",
    "            cx, cy, text=\"💥\",\n",
    "            font=(\"Arial\", 44),\n",
    "            fill=\"black\"\n",
    "        )\n",
    "        # clear hit after short pause\n",
    "        self.master.after(300, self._clear_hit)\n",
    "\n",
    "    def _clear_hit(self):\n",
    "        if self.hit_id:\n",
    "            self.canvas.delete(self.hit_id)\n",
    "            self.hit_id = None\n",
    "\n",
    "    def _end_game(self):\n",
    "        self.game_over = True\n",
    "        # cancel loops\n",
    "        if self.timer_job:\n",
    "            self.master.after_cancel(self.timer_job)\n",
    "        if self.mole_job:\n",
    "            self.master.after_cancel(self.mole_job)\n",
    "        # overlay\n",
    "        overlay = self.canvas.create_rectangle(\n",
    "            0, 0, self.canvas_size, self.canvas_size,\n",
    "            fill=\"black\", stipple=\"gray25\"\n",
    "        )\n",
    "        cx = self.canvas_size//2\n",
    "        cy = self.canvas_size//2\n",
    "        self.canvas.create_text(\n",
    "            cx, cy-30, text=\"Game Over!\",\n",
    "            font=(\"Verdana\", 36, \"bold\"),\n",
    "            fill=\"black\"\n",
    "        )\n",
    "        self.canvas.create_text(\n",
    "            cx, cy+10, text=f\"Your score: {self.score}\",\n",
    "            font=(\"Verdana\", 24),\n",
    "            fill=\"black\"\n",
    "        )\n",
    "\n",
    "    def _on_restart(self):\n",
    "        # cancel loops\n",
    "        if self.timer_job:\n",
    "            self.master.after_cancel(self.timer_job)\n",
    "        if self.mole_job:\n",
    "            self.master.after_cancel(self.mole_job)\n",
    "        # clear overlay, mole, hit\n",
    "        self.canvas.delete(\"all\")\n",
    "        # redraw holes\n",
    "        for r in range(self.rows):\n",
    "            for c in range(self.cols):\n",
    "                x1 = c*self.cell + 20\n",
    "                y1 = r*self.cell + 20\n",
    "                x2 = (c+1)*self.cell - 20\n",
    "                y2 = (r+1)*self.cell - 20\n",
    "                self.canvas.create_oval(x1, y1, x2, y2,\n",
    "                                        fill=\"#8B4513\", outline=\"\")\n",
    "        # reset state & loops\n",
    "        self._reset_state()\n",
    "        self._start_loops()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    WhackAMoleDeluxe(root)\n",
    "    root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cfac41b2-0d83-49a9-84e2-7b32f15c990b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
